version: "3"

services:
  golang:
    tty: true
    build: "./docker/go"
    volumes:
      - ./app:/go/app:z
    ports:
      - "9000"
    restart: always
    command: bash -c "realize start --server"
  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./docker/nginx/log:/var/log/nginx:z
    ports:
      - "80:80"
    depends_on:
      - "golang"
    restart: always