version: "3"

services:
  api:
    tty: true
    build: "./docker/go"
    volumes:
      - ./app:/go/app/api:z
    ports:
      - "80"
    restart: always
    command: bash -c "realize start --server"
  web:
    image: nginx:latest
    volumes:
      - ./docker/web/log:/var/log/nginx:z
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf:z
      - ./app/public:/var/www/html:z
    ports:
      - "80"
    restart: always
  proxy:
    build: ./docker/proxy
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:z
      - ./docker/proxy/log:/var/log/nginx:z
    ports:
        - 80:80
    restart: always