version: "3"

services:
  web:
    image: nginx:latest
    volumes:
      - ./docker/web/log:/var/log/nginx:z
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf:z
      - ./app/public/dist:/var/www/html:z
    ports:
      - "3000"
    restart: always
